library(dplyr)
library(tidyr)
setwd("c:/Users/vidya/downloads")
read.csv("refine_original.csv")
refine_original <- read.csv("C:/Users/vidya/Downloads/refine_original.csv"
)
View(refine_original)
refine_original$company <- tolower(refine_original$company)
idx <- agrep(pattern = "phillips", x = refine_original$company, ignore.case = FALSE, value = FALSE, max.distance = 3)
refine_original$company[idx] <- "phillips"
ikx <- agrep(pattern = "akzo", x = refine_original$company, ignore.case = FALSE, value = FALSE, max.distance = 1)
refine_original$company[ikx] <- "akzo"
refine_original <- separate(refine_original,Product.code...number,c("product_code","product_number"))
categories <- c(p = "smartphone", v = "tv", x = "laptop", q = "tablet")
refine_original <- mutate(refine_original, product.category = categories[refine_original$product_code])
refine_original <- refine_original %>% unite(full_adress,address:country,sep = ",",remove = TRUE)
refine_original$company_phillips <- as.numeric(refine_original$company == "phillips")
refine_original$company_akzo <- as.numeric(refine_original$company =="akzo")
refine_original$company_van_houten <- as.numeric(refine_original$company == "van houten")
refine_original$company_unilever <- as.numeric(refine_original$company == "unilever")
refine_original$product_smartphone <- as.numeric(refine_original$product.category == "smartphone")
refine_original$product_tv <- as.numeric(refine_original$product.category == "tv")
refine_original$product_laptop <- as.numeric(refine_original$product.category == "laptop")
refine_original$product_tablet <- as.numeric(refine_original$product.category == "tablet")
View(refine_original)
